### ISSUE TITLE
Crash on WPS configuration

### ISSUE THREAD

**Issue by bbogush** [prplfoundation/prplMesh-old#6]
scenario:
Start WPS provisioning between two PC with virtual interfaces (interface.eth0.sim).
result:
crash during 1905 communication.
root cause: missing return statement

```
diff --git a/src/al_send.c b/src/al_send.c
index 1caa392..c13514f 100644
--- a/src/al_send.c
+++ b/src/al_send.c
@@ -1599,6 +1599,8 @@ static struct tlv *_obtainLocalRadioBasicCapabilitiesTLV(const struct radio *rad
     apRadioBasicCapabilities->maxbss = (uint8_t) radio->maxBSS;
     memcpy(apRadioBasicCapabilities->radio_uid, radio->uid, 6);
     /* @todo determine classes and inoperable channels */
+
+    return &apRadioBasicCapabilities->tlv;
 }
 
 // Given a pointer to a preallocated "genericPhyDeviceInformationTypeTLV"
```

**Comment by arnout** [comment]
We have abandoned this code base, and replaced it with a different code base to implement the MultiAP functionality.
This repository will be renamed and archived, and the new code base will appear in the same location (https://github.com/prplfoundation/prplMesh).
